### PR TITLE
New site template

### PR DESCRIPTION
**Pull request by hrcn**

### CODE REVIEW

**Comment by jkhartshorne** [comment]
Looks like quizzes are hard-coded. The list should be automatically generated, as was done in the original template.

**Comment by jkhartshorne** [comment]
Have you or @conbainbridge gotten this to run locally? Currently, I'm running into the following error when using react-scripts to do a local deploy: 

`Failed to compile
./src/reducers/index.js
Module not found: Can't resolve 'redux-form' in '/Users/jkhartshorne/Documents/Projects/PushkinDev/PushkinNew/current/pushkin/front-end/src/reducers'`

I get a different issue when I try to deploy using docker, but that may have a different reason.

**Comment by hrcn** [comment]
> Have you or @conbainbridge gotten this to run locally? Currently, I'm running into the following error when using react-scripts to do a local deploy:
> 
> `Failed to compile ./src/reducers/index.js Module not found: Can't resolve 'redux-form' in '/Users/jkhartshorne/Documents/Projects/PushkinDev/PushkinNew/current/pushkin/front-end/src/reducers'`
> 
> I get a different issue when I try to deploy using docker, but that may have a different reason.

Maybe try `npm i --save redux-form`?

**Comment by jkhartshorne** [comment]
I'll try that, but how did this work on your computer? redux-form isn't in the package.json.

**Comment by jkhartshorne** [comment]
@hrcn - looks pretty good. Can you please do three things:

1. Add redux-form to the package.json
2. Adjust the formatting for tablets. When I use the iPad emulator, either the header and footer boxes are much too large **or** the font size in the header and footer need to be increased. 
Screen Shot 2020-06-17 at 8 35 43 AM

3. I'm seeing some errors in Chrome. Two of them might be because I'm not using Docker right now to test this, but here's one that probably can be fixed easily:

`index.js:1 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `QuizPage`. See https://fb.me/react-warning-keys for more information.
    in withRouter(QuizTile) (at Home.js:38)
    in QuizPage (created by Context.Consumer)
    in Route (at App.js:36)
    in div (at App.js:34)
    in App (created by Context.Consumer)
    in withRouter(App) (at src/index.js:56)
    in Router (at src/index.js:55)
    in Provider (at src/index.js:54)
    in Auth0Provider (at src/index.js:48)`

**Comment by hrcn** [comment]
> I'll try that, but how did this work on your computer? redux-form isn't in the package.json.

I guess I npm installed it without adding the `--save`...

**Comment by hrcn** [comment]
> @hrcn - looks pretty good. Can you please do three things:
> 
> 1. Add redux-form to the package.json
> 2. Adjust the formatting for tablets. When I use the iPad emulator, either the header and footer boxes are much too large **or** the font size in the header and footer need to be increased.
>    Screen Shot 2020-06-17 at 8 35 43 AM
> 3. I'm seeing some errors in Chrome. Two of them might be because I'm not using Docker right now to test this, but here's one that probably can be fixed easily:
> 
> `index.js:1 Warning: Each child in a list should have a unique "key" prop.
> 
> Check the render method of `QuizPage`. See https://fb.me/react-warning-keys for more information.
> in withRouter(QuizTile) (at Home.js:38)
> in QuizPage (created by Context.Consumer)
> in Route (at App.js:36)
> in div (at App.js:34)
> in App (created by Context.Consumer)
> in withRouter(App) (at src/index.js:56)
> in Router (at src/index.js:55)
> in Provider (at src/index.js:54)
> in Auth0Provider (at src/index.js:48)`

Just added the redux-form to package.json, and key props to the QuizTile, FindingsCard components.

image

image

As for for the formatting for tablets, I think it looks ok when simulating iPad in my chrome. Should I increase the font size in header and footer?

**Comment by jkhartshorne** [comment]
"As for for the formatting for tablets, I think it looks ok when simulating iPad in my chrome. Should I increase the font size in header and footer?" <- yes, please do that.

**Comment by hrcn** [comment]
> "As for for the formatting for tablets, I think it looks ok when simulating iPad in my chrome. Should I increase the font size in header and footer?" <- yes, please do that.

How about this?

image

image

**Pull request merged**
